var DB_LOCATION = '../db/CS.sqlite';
exports.DB_LOCATION = DB_LOCATION;
var EXTRACT_SIZE = 23;
exports.EXTRACT_SIZE = EXTRACT_SIZE;
var MAX_PER_WRITING = 2;
exports.MAX_PER_WRITING = MAX_PER_WRITING;
var MAX_PER_AUTHOR = 2;
exports.MAX_PER_AUTHOR = MAX_PER_AUTHOR;
//# sourceMappingURL=const.js.map